spring:
  application:
    name: api-gateway
  config:
    import:
      - classpath:routes/routes.yaml
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 20
        minimumNumberOfCalls: 3
        slidingWindowSize: 5
        waitDurationInOpenState: 1s
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      driverServiceCircuitBreaker:
        base-config: default
      financeServiceCircuitBreaker:
        base-config: default
      passengerServiceCircuitBreaker:
        base-config: default
      rideServiceCircuitBreaker:
        base-config: default
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
#  instance:
#    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
server:
  port: 8070