spring:
  application:
    name: finance-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
  artemis:
    broker-url: ${SPRING_ARTEMIS_BROKER_URL}
    user: ${SPRING_ARTEMIS_USER}
    password: ${SPRING_ARTEMIS_PASSWORD}
  messages:
    basename: messages
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application:
        name: ${spring.application.name}
server:
  port: 8084