spring:
  application:
    name: driver-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  messages:
    basename: messages
    encoding: UTF-8
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: driver-event
  artemis:
    mode: native
    user: ${SPRING_ARTEMIS_USER}
    password: ${SPRING_ARTEMIS_PASSWORD}
    broker-url: ${SPRING_ARTEMIS_BROKER_URL}
  cloud:
    openfeign:
      client:
        config:
          finance-service:
            url: http://localhost:8084/api/v1/finance
          passenger-service:
            url: http://localhost:8081/api/v1/rates
          ride-service:
            url: http://localhost:8083/api/v1/rides
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application:
        name: ${spring.application.name}


server:
  port: 8082