spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: driver-event
  liquibase:
    enabled: false
    change-log: db/changelog/changelog.xml
  artemis:
    mode: native
    user: ${SPRING_ARTEMIS_USER}
    password: ${SPRING_ARTEMIS_PASSWORD}
    broker-url: ${SPRING_ARTEMIS_BROKER_URL}
  cloud:
    openfeign:
      client:
        config:
          finance-service:
            url: http://localhost:8084/api/v1/finance
          passenger-service:
            url: http://localhost:8081/api/v1/passengers
  messages:
    basename: messages
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include:  "*"
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application:
        name: ${spring.application.name}
server:
  port: 8083