spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${KAFKA_CONSUMER}
  artemis:
    mode: native
    user: ${ARTEMIS_USER}
    password: ${ARTEMIS_PASSWORD}
    broker-url: tcp://artemis:${ARTEMIS_PORT}
  cloud:
    openfeign:
      client:
        config:
          finance-service:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_FINANCE_SERVICE_URL}
          passenger-service:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_PASSENGER_SERVICE_URL}
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8083