spring:
  application:
    name: passenger-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_DRIVER_SERVICE_URL}
          ride-service:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_RIDE_SERVICE_URL}
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: ${SERVER_PORT:-8081}