spring:
  application:
    name: passenger-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: http://localhost:8082/api/v1/drivers
          ride-service:
            url: http://localhost:8083/api/v1/rides
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 8081