spring:
  application:
    name: passenger-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          driver-service:
            url: http://localhost:8082/api/v1/drivers
          ride-service:
            url: http://localhost:8083/api/v1/rides
  messages:
    basename: messages
    encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      service: passenger-service
  elastic:
    metrics:
      export:
        enabled: true
        host: ${ES_URL}
        index: passenger-metrics
        auto-create-index: false
        timestamp-field-name: "@timestamp"
        step: 1m
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 8081